name: Build Windows Executable

on:
  push:
    branches:
      - TESTING
  pull_request:
    branches:
      - TESTING

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile pkgs.py
          pyinstaller --onefile pkgs-exe.py

      - name: Upload Release Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows-executables
          path: |
            dist/pkgs.exe
            dist/pkgs-exe.exe

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)
          
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: TESTING
